<div id="video">
    <object width="640" height="390">
        <param name="movie"
               value="<?php echo $this->video_url ?>"></param>
        <param name="allowScriptAccess" value="always"></param>
        <embed src="<?php echo $this->video_url ?>"
               type="application/x-shockwave-flash"
               allowscriptaccess="always"
               width="640" height="390"></embed>
    </object>
</div>