<div id="video">
    <object width="680" height="414">
        <param name="movie" value="<?php echo $this->video_url ?>" />
        <param name="allowScriptAccess" value="always" />
        <param name="allowFullScreen" value="true" />
        <embed src="<?php echo $this->video_url ?>" type="application/x-shockwave-flash"
               allowscriptaccess="always" width="680" height="414" allowfullscreen="true"></embed>
    </object>
</div>