<?php echo $this->doctype() ?>
<html>
    <head>
        <?php echo $this->headMeta() ?>
        <?php echo $this->headTitle() ?>
        <?php echo $this->headLink() ?>
        <?php echo $this->headStyle() ?>
        <?php echo $this->headScript() ?>
    </head>
    <body>
        <div class="wrap">
            <header>
                <div class="content">
                    <h1><a href="<?php echo $this->link('')?>" title="Home">Application for Music</a></h1>
                    <p>System integration with the Youtube, Last.fm and Vagalume.</p>
                    <?php if ($this->user): ?>
                        <div class="user">
                            Hello <span><?php echo $this->user->name ?></span>
                            <a href="<?php echo $this->link('index/logout') ?>" title="Logout">(Logout)</a>
                        </div>
                    <?php endif ?>
                </div>
            </header>
            <div id="content">
                <?php echo $this->layout()->content ?>
            </div>
            <footer>
                <div class="content">
                    Programação II - Trabalho (T2)<br />
                    © 2012 - Anderson Eduardo Barberini / Artur Magalhães        
                </div>
            </footer>
        </div>
    </body>
</html>