<div class="login">
    <h2>Login</h2>
    <form action="<?php echo $this->link('login/doauth') ?>" method="POST">
        <div class="row">
            <label for="username">Username:</label>
            <input type="text" name="username" class="text" id="username" />
        </div>
        <div class="row">
            <label for="password">Password:</label>
            <input type="password" class="text" name="password" id="password" />
        </div>
        <?php if (!is_null($this->error) && $this->error == 1): ?>
            <div class="error">Username or password is invalid.</div>
        <?php endif; ?>    
        <input type="submit" class="submit" value="Log In" />
    </form>    
    <a href="<?php echo $this->baseUrl('login/signup') ?>" title="Sign up">New user? Sign up.</a>
</div>