<div class="cadastro">
    <h2>Sign Up</h2>
    <form action="<?php echo $this->link('login/dosign') ?>" method="POST">
        <div class="row">
            <label for="name">Name:</label>
            <input type="text" name="name" class="text" value="<?php echo $this->user->name ?>" id="name" />
        </div>
        <div class="row">
            <label for="email">E-mail:</label>
            <input type="text" name="email" class="text" value="<?php echo $this->user->email ?>" id="email" />
        </div>
        <div class="row">
            <label for="nickname">Username:</label>
            <input type="text" name="username" class="text" value="<?php echo $this->user->username ?>" id="username" />
        </div>
        <div class="row">
            <label for="password">Password:</label>
            <input type="password" name="password" class="text" value="<?php echo $this->password ?>" id="password" />
        </div>
        <?php if (!is_null($this->error)): ?>
            <div class="error">
                <?php
                if ($this->error == 1) {
                    echo 'Complete all the fields correctly.';
                }
                if ($this->error == 2) {
                    echo 'This email is already registered.';
                }
                if ($this->error == 3) {
                    echo 'This username is already registered.';
                }
                ?>
            </div>
        <?php endif; ?>
        <input type="submit" class="submit" value="Sign Up" />
    </form>
    <a href="<?php echo $this->baseUrl('login') ?>" title="Sign up">Already registered? Log In.</a>
</div>